# Generated by Django 4.2.13 on 2024-07-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmMangment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="type",
            field=models.CharField(
                choices=[
                    ("Fruits", "Fruits"),
                    ("Vegetables", "Vegetables"),
                    ("Legumes", "Legumes"),
                    ("Grains", "Grains"),
                ],
                max_length=255,
            ),
        ),
    ]
